### PR TITLE
Blocked TNT Water Lava etc Closes #85

### LINKED ISSUE #85: TNT & Similar Blocking
Currently there are no restrictions on blocking items from being used. This needs to be added especially for explosions, lava flow and similar.

### PR DESCRIPTION
**Pull request by GotNoFriends**

### CODE REVIEW

**Comment by GotNoFriends** [comment]
@Wild1145

**Comment by Wild1145** [comment]
This should all be handled in a module really, the listeners should just call the module.

**Comment by GotNoFriends** [comment]
Ah sorry.

**Comment by Wild1145** [comment]
No worries, just something we wanted to implement here to easily enable and disable functionality if we want to.

**Comment by Wild1145** [comment]
@GotNoFriends Any updates? This is also no longer able to be merged in with the main branch.

**Comment by Wild1145** [comment]
Closed for inactivity.

**Pull request closed without merging**
