### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mayokek**
Correct the location of the gitter chat thingy

### CODE REVIEW

**Comment by Hockeyfan360** [comment]
It just doesnt look good...

**Comment by mayokek** [comment]
You don't have to merge it but yea.

**Comment by Hockeyfan360** [comment]
Sorry, misread. Thanks for your contrib :smile:

**Comment by Wild1145** [comment]
I cannot see a change...

**Comment by Hockeyfan360** [comment]
My bad, didn't see that either. Oh, what being on vacation does to you....

**Pull request merged**
