### PR TITLE
Update SeniorAdminChat.java

### PR DESCRIPTION
**Pull request by GotNoFriends**
@Hockeyfan360 You forgot a space.

### CODE REVIEW

**Comment by Wild1145** [comment]
What is the actual symbol being used?? The color code one... It looks strange and not quite a &...

**Comment by GotNoFriends** [comment]
That is a alternative to the &

**Comment by Wild1145** [comment]
If thats the case, then spaces break shit if I remember. You want a space before the color code. Or after the previous :'s

**Comment by GotNoFriends** [comment]
I don't think thats it, I used some of this code for a project of mine and it needed a space

**Comment by Wild1145** [comment]
I have never used this way of color coding, so I will take a look in more detail tomorrow to confirm.

**Comment by GotNoFriends** [comment]
@Hockeyfan360 could you explain in more detail?

**Comment by Wild1145** [comment]
Thinking about it, color codes or no color codes, there should well be a space there.

**Pull request merged**
