### PR TITLE
Update Command_ban.java

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
Just a ban reason and who banned you.

### CODE REVIEW

**Comment by Wild1145** [comment]
Looks good to me. Just needs to be tested and then away we go!

**Comment by mgejay** [comment]
May I suggest adding an Appeal url to this when a forums is created?

**Comment by Wild1145** [comment]
That would be smart. I need to speak to @CameronRedmore and have some sort of MySQL Config system setup, but there ideally would be a MySQL based appeal URL. I think however that can be added at a later date when we have MySQL config systems properly working.

**Comment by Wild1145** [comment]
The code does not compile. You are missing the import for your chat colours.

**Comment by LegendIsAwesomes** [comment]
@Wild1145 I'll add that it about 3 hours

**Comment by Wild1145** [comment]
Closed for inactivity.

**Pull request closed without merging**
