### PR TITLE
Kick command *Improved*

### PR DESCRIPTION
**Pull request by mgejay**
^^^

### CODE REVIEW

**Comment by mgejay** [comment]
@Wild1145 
@Hockeyfan360

**Comment by Hockeyfan360** [comment]
Use allmans style.

**Comment by Hockeyfan360** [comment]
As you have already made three commits in this pr, I am going to recommend that you close this, @Wild1145

**Comment by Wild1145** [comment]
It would be nice to have it in one commit, but its not the end of the world.

**Comment by Wild1145** [comment]
Closed for inactivity.

**Pull request closed without merging**
