### PR TITLE
Blocks lava etc

### PR DESCRIPTION
**Pull request by GotNoFriends**
Tested.

### CODE REVIEW

**Comment by Wild1145** [comment]
This wont currently work as the module has to be properly created.

**Comment by GotNoFriends** [comment]
@Wild1145 What do you mean?

**Comment by Wild1145** [comment]
The modules dont just work, you have to register the modules in the main class file and then using the actual listeners execute the parts of the modules like the other modules work.

**Comment by GotNoFriends** [comment]
@Wild1145 I added them into my plugin on the main class, just didn't create a pull yet.

**Comment by Wild1145** [comment]
You will need to make sure you put it on the same branch so that this PR updates.

**Comment by GotNoFriends** [comment]
Okay.

**Comment by GotNoFriends** [comment]
@Wild1145 Done.

**Comment by Wild1145** [comment]
Will take a proper look when I get on my Desktop

**Comment by GotNoFriends** [comment]
Alrighty

**Comment by Wild1145** [comment]
The code in its current state cannot compile. It also cannot be merged with the main branch. Please fix these issues before we can pull it in.

**Comment by Wild1145** [comment]
@GotNoFriends Any updates?

**Comment by Wild1145** [comment]
Closed for inactivity.

**Pull request closed without merging**
